### ISSUE TITLE
Ampy able to upload binary files... but unable to download them.

### ISSUE THREAD

**Issue by joewez** [scientifichackers/ampy#45]
Not a major issue, but I was just wondering if this was more of an oversight rather than an actual deficiency.  I'm mean if it works one way... why not the other? 

I am running Python 3 on Windows 10.

**Comment by ladyada** [comment]
Hiya! We are discontinuing support for ampy, and will no longer be maintaining it. We are leaving this repository available for continued use. If you would like to take over supporting it, please contact us on the Adafruit Discord server and we can transfer the repository to you.
If you wish to continue developing it on your own, please fork the repository.

**Comment by curiouswala** [comment]
Currently the file transfer happens over Serial communication which have a lot of bugs specially in the case of binary files. We will be releasing a v2 soon which works over WIFI and solves the above problem.
