### ISSUE TITLE
Can the short timeout when calling Pyboard.follow() through ampy run command be removed?

### ISSUE THREAD

**Issue by cs0ckn** [scientifichackers/ampy#54]
When `Pyboard.exec_raw()` calls `Pyboard.follow()` and a `timeout=10` is defaulted, this only gives a short time (I assume around 10 seconds) before the `ampy run` command without `--no-output` will raise `PyboardError('timeout waiting for first EOF reception')`. This is a problem if you have a long running program from which you wish to see output in a terminal window (I'm running on Windows 10) when it completes (you just get the pyboard error message).
I have modded `def exec_raw(self, command, timeout=10, data_consumer=None):` in `pyboard.py` to have a default `timeout=None` which allows `ampy run` to continue until the program running on the pyboard (in my case an ESP32) completes.
Is this a reasonable change that can be made or will it affect other operations?

**Comment by ladyada** [comment]
Hiya! We are discontinuing support for ampy, and will no longer be maintaining it. We are leaving this repository available for continued use. If you would like to take over supporting it, please contact us on the Adafruit Discord server and we can transfer the repository to you.
If you wish to continue developing it on your own, please fork the repository.
