### ISSUE TITLE
bad interpreter

### ISSUE THREAD

**Issue by m0ot** [scientifichackers/ampy#77]
I cant understand why I newly get this error when I try to start working with ampy ???? It makes me crazy

bash: /home/linuxbrew/.linuxbrew/bin/ampy: /home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.15_1/bin/python: bad interpreter: No such file or directory

**Comment by infogeek** [comment]
This looks like a problem with your python installation. Can you confirm you have a working python installtion?
