### ISSUE TITLE
ampy broken on win10

### ISSUE THREAD

**Issue by gitandy** [scientifichackers/ampy#78]
Newest ampy is broken due to missing default delay value in pyboard.py enter_raw_repl()
The first if should be extended with an else followed by somthing like time.sleep(1)

if _rawdelay > 0:
  time.sleep(_rawdelay)
else:
  time.sleep(1)

**Comment by devxpy** [comment]
So it works fine if you supply `--delay`?

**Comment by gitandy** [comment]
Thanks for your reply. It's a long time ago and I can't remeber what went wrong anymore. 
Also I solved problems with the board if there a to short delay in the main loop. 

Currently it works and I learned to use the .ampy file to have a permanent setting of the delay.
So sorry.
