### ISSUE TITLE
improve RTS/DTR control

### ISSUE THREAD

**Issue by camelator** [scientifichackers/ampy#79]
Ampy does not connect to MaixPi board with Ubuntu 18.04
As explain here:
https://github.com/dhylands/rshell/issues/91
this is related to the RTS / DTR settings in the constructor of class Serial.
adding these two lines in file pyboard.py correct the bug (like the miniterm source code).
                    self.serial.rts=False
                    self.serial.dtr=False
Unfortunately I am not a python developper, maybe someone can add some command line parameter ?

**Comment by curiouswala** [comment]
I don't have a  MaixPi board to test this and it's not officially supported.
