### ISSUE TITLE
Make a new release to PyPI please

### ISSUE THREAD

**Issue by mludvig** [scientifichackers/ampy#99]
The [`adafruit-ampy` release on pypi](https://pypi.org/project/adafruit-ampy/) is very old (October 2018) with a number of annoying bugs that have been fixed over the years.

Any chance you could tag a new release and push it to PyPI? Please :)

**Comment by curiouswala** [comment]
Agreed. I'll need some time to run all the tests before the release. I'll try to do it before the end of this month. Meanwhile, we are working on a complete rewrite of Ampy which fixes a lot of the past issues by using WIFI instead of USB. Will release an ALPHA soon, Stay tuned.

**Comment by curiouswala** [comment]
Done. :)
